report: "report/workflow.rst"

configfile: "config/config.yaml"

include: "rules/common.smk"

for rulefile in ANI_RULES:

    include: rulefile

include: TREE_RULES


rule all:
    """
    Collect all final outputs to drive the full pipeline.
    """
    input:
        expand("results/QC/quast/{sample}.pdf", sample=SAMPLES),
        "results/QC/gene-qc-matrix.pdf",
        "results/phylogenetics/MLSA.nwk",
        ANI_TARGETS,
        TREE_TARGETS,
        PUBLIC_GENOME_TARGETS,


rule get_genome:
    """
    Download genome assembly from NCBI Datasets and move it to the expected location.
    """
    output:
        fasta="resources/public_genomes/{sample}.fna",
        zip=temp("resources/datasets/{sample}.zip"),
        dir=temp(directory("resources/datasets/{sample}"))
    wildcard_constraints:
        sample=ACCESSION_SAMPLES
    conda:
        "envs/ncbi-datasets.yaml"
    log:
        "logs/datasets/{sample}.log",
    params:
        accession=lambda wildcards: accessions.loc[wildcards.sample, 'assembly']
    shell:
        """
        exec > {log} 2>&1
        datasets download genome accession {params.accession} --include genome --filename {output.zip}
        unzip {output.dir}.zip -d {output.dir}
        mv {output.dir}/ncbi_dataset/data/{params.accession}/{params.accession}*_genomic.fna {output.fasta}
        """

rule validate_ref_genes:
    """
    Validate reference gene FASTA headers.
    """
    input:
        REF_GENES,
    output:
        report=touch("results/QC/ref_genes.validated"),
        fasta="resources/db/ref-genes.validated.fas",
    log:
        "logs/ref_genes_validation.log",
    conda:
        "envs/biopython.yaml"
    script:
        "scripts/validate-ref-genes.py"


rule quast:
    """
    Assess assembly quality with QUAST and produce a PDF report.
    """
    input:
        fasta=genome_file
    output:
        report_pdf=report(
            "results/QC/quast/{sample}.pdf",
            caption="report/qc.rst",
            category="QC",
        )
    log:
        "logs/QUAST/{sample}.log"
    threads: min(8, workflow.cores)
    params:
        extra="--fungus --min-contig 5 --min-identity 95.0"
    wrapper:
        "v9.9.0/bio/quast"


rule minimap2:
    """
    Map reference genes against each genome assembly with minimap2.
    """
    input:
        target=genome_file,
        query="resources/db/ref-genes.validated.fas",
        validated_ref="results/QC/ref_genes.validated",
    output:
        temp("results/minimap2/{sample}_mapping.sam"),
    log:
        "logs/minimap/{sample}_minimap2.log",
    threads: workflow.cores
    params:
        extra="-x map-ont -p 0.5", # may need a more relaxed secondary hits '-p 0.5'
        sorting="none",
    wrapper:
        "v9.9.0/bio/minimap2/aligner"


rule sam_filter:
    """
    Filter SAM alignments: remove unmapped reads, flip strands, and keep the single best hit per locus.
    """
    input:
        IN_SAM=("results/minimap2/{sample}_mapping.sam"),
    output:
        F_SAM=temp("results/minimap2/{sample}_mapping_filtered.sam"),
    log:
        "logs/minimap/{sample}_samtools.log",
    threads: workflow.cores
    conda:
        "envs/sam-harmonization.yaml"
    shell:
        """
        samtools view {input.IN_SAM} -F4 -h \
            | sam-flip.pl \
            | sam-keep-best.pl -rid -l -n=1 -po=0.1 \
                >{output.F_SAM} 2>>{log}
        """


rule sam_realign:
    """
    Realign filtered hits against the reference genes for accurate boundary trimming.
    """
    input:
        "results/minimap2/{sample}_mapping_filtered.sam",
        "resources/db/ref-genes.validated.fas",
        genome_file,
    output:
        temp("results/sam_realign/{sample}_realigned_mapping.sam"),
    log:
        "logs/sam_realign/{sample}.log",
    conda:
        "envs/realign.yaml"
    script:
        "scripts/sam-realign.sh"


rule sam_extract_hit_seq:
    """
    Extract hit sequences from realigned SAM files.
    """
    input:
        "results/sam_realign/{sample}_realigned_mapping.sam",
    output:
        temp("results/genes/map_raw/{sample}.fas"),
    threads: min(4, workflow.cores)
    params:
        sim=0.7,
    conda:
        "envs/sam-harmonization.yaml"
    shell:
        """
        cat {input} \
            | sam-filter.pl -minsim={params.sim} \
            | sam-extract-hit-seq.pl \
            > {output}
        """


rule rename_extracted_hit_seq:
    """
    Rename FASTA headers of extracted hit sequences to include the sample name.
    """
    input:
        "results/genes/map_raw/{sample}.fas"
    output:
        temp("results/genes/map/{sample}.fas")
    script:
        "scripts/rename-extracted-hit-fasta.sh"


rule join_fragments:
    """
    Merge fragmented gene hits from the same locus into a single contiguous sequence.
    """
    input:
        "results/genes/map/{sample}.fas",
    output:
        "results/genes/join-fragments/{sample}.fas",
    log:
        "logs/join-fragments/{sample}.log",
    script:
        "scripts/join-fragments.sh"


rule genes_deduplicate:
    """
    Remove exact-duplicate gene sequences within each sample.
    """
    input:
        "results/genes/join-fragments/{sample}.fas",
    output:
        "results/genes/deduplicated/{sample}.fas",
    log:
        "logs/genes_deduplicate/{sample}.log",
    conda:
        "envs/biopython.yaml"
    script:
        "scripts/genes_deduplicate.py"


rule map_all:
    """
    Concatenate per-sample gene FASTAs into a single pool for joint QC and alignment.
    """
    input:
        expand("results/genes/deduplicated/{sample}.fas", sample=SAMPLES),
    output:
        "results/genes/map-pool/map-pool.fas",
    shell:
        """
        cat {input} >{output}
        """


rule genes_qc:
    """
    QC gene hits: check coverage, copy number, and fragmentation; output passing samples and filtered FASTA.
    """
    input:
        fasta="results/genes/map-pool/map-pool.fas",
        ref="resources/db/ref-genes.validated.fas",
        validated_ref="results/QC/ref_genes.validated",
        public_genome_files=expand("resources/public_genomes/{sample}.fna", sample=PUBLIC_GENOMES),
        local_genome_files=expand("{genome}", genome=LOCAL_GENOMES),
    output:
        detail="results/QC/gene-qc-detail.tsv",
        matrix="results/QC/gene-qc-matrix.tsv",
        filtered="results/genes/map-pool/map-pool.filtered.fas",
        sample_lists="results/QC/genome-list-pass.txt",
    log:
        log="logs/genes-qc.log",
    conda:
        "envs/genes-qc.yaml"
    threads: min(4, workflow.cores)
    script:
        "scripts/genes-qc.py"


rule table_plot:
    """
    Plot gene count matrix as a PDF report.
    """
    input:
        tsv="results/QC/gene-qc-matrix.tsv",
    output:
        pdf=report(
            "results/QC/gene-qc-matrix.pdf", caption="report/gene_presence.rst", category="QC"
        ),
    conda:
        "envs/R.yaml"
    script:
        "scripts/table-plot.R"


rule align:
    """
    Extract and align sequences for a single gene across all passing samples with MUSCLE.
    """
    input:
        "results/genes/map-pool/map-pool.filtered.fas",
    output:
        "results/genes/aligned/{gene}.fas",
    log:
        "logs/muscle/{gene}.log",
    threads: min(4, workflow.cores)
    conda:
        "envs/align.yaml"
    shell:
        """
        cat {input} | fasta_grep {wildcards.gene} | muscle >{output} 2>{log}
        """


rule concat:
    """
    Concatenate per-gene alignments into a single multi-locus supermatrix for phylogenetics.
    """
    input:
        expand("results/genes/aligned/{gene}.fas", gene=config["genes"]),
    output:
        fas="results/genes/concat/concat.fas",
        tab="results/genes/concat/concat.tab",
    threads: min(4, workflow.cores)
    conda:
        "envs/fasta_tools.yaml"
    params:
        regex=autoconcatenate_regex
    shell:
        """
        fasta_autoconcatenate -r='{params.regex}' {input} >{output.fas} 2>{output.tab}
        """


rule partition_file:
    """
    Convert the concatenation table into a partition file.
    """
    input:
        "results/genes/concat/concat.tab",
    output:
        "results/genes/concat/concat.part",
    params:
        regex=parition_regex
    shell:
        """
        perl -ne '{params.regex}' {input} >{output}
        """


rule reroot_tree:
    """
    Reroot the best-scoring tree at the midpoint using newick-utils.
    """
    input:
        TREE_OUTPUT,
    output:
        "results/phylogenetics/MLSA.nwk",
    log:
        "logs/reroot_tree.log",
    conda:
        "envs/newick_utils.yaml"
    shell:
        """
        nw_reroot -s {input} >{output} 2>{log}
        """


rule ani_table:
    """
    Reshape pairwise ANI output into a square identity matrix.
    """
    input:
        "results/ANI/{ani_method}/{ani_method}_pairs.tsv",
    output:
        "results/ANI/{ani_method}/{ani_method}_table.tsv",
    log:
        log="logs/ANI/{ani_method}/ani2table.log"
    script:
        "scripts/ani2table.py"


rule ani_plot:
    """
    Plot ANI heatmap alongside the phylogenetic tree as a PDF figure.
    """
    input:
        tree=lambda wc: ANI_PLOT_INPUT[wc.pdf]["tree"],
        ani=lambda wc: ANI_PLOT_INPUT[wc.pdf]["ani"],
    output:
        pdf=report("{pdf}", caption="report/ani.rst", category="ANI"),
    log:
        "logs/ANI/ani_plot_{pdf}.log",
    wildcard_constraints:
        pdf="|".join(ANI_PLOT_INPUT.keys()).replace("/", "\\/"),
    threads: min(4, workflow.cores)
    conda:
        "envs/ani-typer.yaml"
    script:
        "scripts/tree-ANI-heatmap.R"