configfile: "config.yaml"

include: "rules/common.smk"

for rulefile in ANI_RULES:
    include: rulefile

include: TREE_RULES

rule all:
    input:
        "quast/report.pdf",
        "phylogenetics/MLSA.nwk",
        ANI_TARGETS,
        TREE_TARGETS,
        PUBLIC_GENOME_TARGETS

rule download_public_genome:
    """
    Download a public genome from NCBI.
    """
    output:
        "public_genomes/{accession}.fna"
    shell:
        """
        mkdir -p public_genomes

        datasets download genome accession \
            {wildcards.accession} \
            --include genome \
            --filename {wildcards.accession}.zip

        unzip -oq {wildcards.accession}.zip -d {wildcards.accession}

        cp $(find {wildcards.accession} -name "*.fna" | head -n 1) {output}

        rm -rf {wildcards.accession}
        rm -f {wildcards.accession}.zip
        """

# Annotate genomes
# rule prokka:
#     """
#     Annotate genome assemblies using prokka
#     """
#     input:
#         "genomes/{sample}.fna"
#     output:
#         "annotation/{sample}/{sample}.fna", # Genome sequences (with contig names matching with gff)
#         #"annotation/{sample}/{sample}.log", # log
#         #"annotation/{sample}/{sample}.faa", # Protein sequences
#         #"annotation/{sample}/{sample}.ffn",  # gene sequences also rRNA
#         "annotation/{sample}/{sample}.gff" # GFF annotation
#     threads: 8
#     shell:
#         "prokka {input} --force --cpus {threads} --outdir annotation/{wildcards.sample} --prefix {wildcards.sample} --centre BioInt --compliant"




rule gff:
    input:
        "annotation/{sample}/{sample}.gff",
        "mlsa.yml",
        "annotation/{sample}/{sample}.fna"
    output:
        "genes/gff/{sample}.fas"
    shell:
        """
        perl {gff3filter} {input[0]} {input[1]} |
        perl {gff3extract} - {input[2]} |
        workflow/scripts/rename-extracted-gff-fasta.pl - -sample={wildcards.sample} > {output}
        """


rule gff_all:
    input:
        expand("genes/gff/{sample}.fas", sample=SAMPLES)
    output:
        "genes/gff-pool.fas"
    shell:
        """
        cat {input} > {output}
        """


# Assembly quality check
rule validate_ref_genes:
    input:
        "db/ref-genes.fas"
    output:
        report=touch("report/ref_genes.validated"),
        fasta="db/ref-genes.validated.fas"
    log:
        "logs/ref_genes_validation.log"
    shell:
        """
        python workflow/scripts/validate-ref-genes.py \
            {input} \
            {output.report} \
            {output.fasta} \
            > {log} 2>&1
        """

rule quast:
    input:
        fasta=GENOMES
    output:
        file_pdf="quast/report.pdf"
    log:
        "logs/quast.log"
    conda:
        "envs/quast.yaml"
    params:
        outdir="quast"
    threads:
        workflow.cores
    shell:
        """
        quast.py {input.fasta} \
            -o {params.outdir} \
            --fungus \
            --min-contig 5 \
            --min-identity 95.0 \
            --threads {threads} \
            > {log} 2>&1
        """

# Rule build gene base
# Cat .fas .fasta .fna etc to a ref-genes.fas and go on..
# Extract gene names so we do not need the config.yaml 


rule minimap:
    input:
        IN_GENOME=genome_file,
        IN_DATABASE="db/ref-genes.validated.fas",
        validated_ref="report/ref_genes.validated"
    output:
        OUT_SAM=temp("minimap/{sample}_mapping.sam"),
        F_SAM=temp("minimap/{sample}_mapping_filtered.sam")
    threads:
        workflow.cores
    log:
        "logs/minimap/{sample}.log"
    shell:
        """
        minimap2 -a -x map-ont {input.IN_GENOME} {input.IN_DATABASE} > {output.OUT_SAM} 2> {log} 

        samtools view {output.OUT_SAM} -F4 -h |
        sam-flip.pl |
        sam-keep-best.pl -rid -l -n=1 -po=0.1 \
        > {output.F_SAM} 2>> {log}
        """


rule sam_realign:
    input:
        IN_HITS="minimap/{sample}_mapping_filtered.sam",
        IN_DATABASE="db/ref-genes.validated.fas",
        IN_QUERY=genome_file,
        validated_ref="report/ref_genes.validated"
    output:
        OUT_SAM=temp("sam_realign/{sample}_realigned_mapping.sam")
    threads:
        4
    log:
        "logs/sam_realign/{sample}.log"
    shell:
        """
        workflow/scripts/sam-realign.pl {input.IN_HITS} {input.IN_DATABASE} {input.IN_QUERY} > {output.OUT_SAM} 2> {log}
        """


## extract locus sequences
rule sam_extract_hit_seq:
    input:
        IN="sam_realign/{sample}_realigned_mapping.sam"
    output:
        OUT=temp("genes/map/{sample}.fas")
    params:
        sim=0.7
    threads:
        4
    shell:
        """
        cat {input.IN} |
        sam-filter.pl -minsim={params.sim} |
        sam-extract-hit-seq.pl |
        workflow/scripts/rename-extracted-hit-fasta.pl - -sample={wildcards.sample} > {output.OUT}
        """

rule map_all:
    input:
        expand("genes/map/{sample}.fas", sample=SAMPLES)
    output:
        "genes/map-pool/map-pool.fas"
    threads:
        4
    shell:
        """
        cat {input} > {output}
        """

rule gene_qc:
    input:
        fasta="genes/map-pool/map-pool.fas",
        ref="db/ref-genes.validated.fas",
        validated_ref="report/ref_genes.validated"
    output:
        detail="report/gene-qc-detail.tsv",
        summary="report/gene-qc-summary.tsv",
        filtered="genes/map-pool/map-pool.filtered.fas",
        sample_lists="report/genome-list-pass.txt"
    threads:
        4
    log:
        log="logs/gene-qc.log",
        report="report/gene-qc.log"
    shell:
        """
        python workflow/scripts/genes-qc.py \
            {input.fasta} \
            {input.ref} \
            {output.detail} \
            {output.summary} \
            {output.filtered} \
            {output.sample_lists} \
            {log.log} 2> {log.report}
        """

rule align:
    input:
        "genes/map-pool/map-pool.filtered.fas"
    output:
        "genes/aligned/{gene}.fas"
    threads:
        4
    log:
        "logs/muscle/{gene}.log"
    shell:
        """
        cat {input} | fasta_grep {wildcards.gene} | muscle > {output} 2> {log}
        """

rule concat:
    input:
        expand("genes/aligned/{gene}.fas", gene=config["genes"])
    output:
        fas="genes/concat/concat.fas",
        tab="genes/concat/concat.tab"
    threads: 
        4
    shell:
        """
        fasta_autoconcatenate -r='{autoconcatenate_regex}' {input} > {output.fas} 2> {output.tab}
        """

rule partition_file:
    input:
        "genes/concat/concat.tab"
    output:
        "genes/concat/concat.part"
    shell:
        """
        perl -ne '{parition_regex}' {input} > {output}
        """