# Sample sheets for the workflow
accessions: config/public_genomes.tsv
local_samples: config/local.tsv

# Gene/locus selection for MLSA
genes:
  - BenA
  - RPB2
  - CaM
  - Act

# Method for extracting target genes [mapping, amplicon]
extraction_method: amplicon

# Tree configuration
tree:
  method: iqtree
  bootstrap: 1000

# ANI configuration
ani_method: skani

# Reference gene database
ref_genes: config/ref-genes.fas
filtering:
  # The minimum similarty to keep a hit for extraction when mapping
  minimum_similarity: 0.65
  # Amplicon filtering parameters
  min_amplicon_length: 50
  max_amplicon_length: 5000
  max_total_mismatches: 5
  reject_primer_from: 4

# Primer sheet for amplicon extraction
primers: "config/primers.tsv"
