# Gene configuration
genes:
  - calmodulin
  - actin
  - rpb2
  - benA

# Tree configuration
tree:
  method: iqtree
  bootstrap: 1000

# ANI configuration
ani_method: skani

# Optional, define public genomes to include in the analysis. 
accessions: config/public_genomes.txt

# Optional change labels in phylogeny + ANI plot
sample_labels: config/sample_metadata.tsv