$schema: "http://json-schema.org/draft-07/schema#"

type: object

properties:

  ani_method:
    type: string
    enum:
      - none
      - fastani
      - pyani
      - skani
    default: fastani

  include_reference:
    type: boolean
    default: false

  genes:
    type: array
    minItems: 1
    items:
      type: string

  tree:
    type: object

    properties:

      method:
        type: string
        enum:
          - raxml
          - iqtree
          - fasttree
        default: iqtree

      bootstrap:
        type: integer
        minimum: 1
        default: 1000

    required:
      - method

    allOf:

      # RAxML
      - if:
          properties:
            method:
              const: raxml
        then:
          required:
            - bootstrap
          properties:
            bootstrap:
              type: integer
              minimum: 1

      # IQ-TREE
      - if:
          properties:
            method:
              const: iqtree
        then:
          required:
            - bootstrap
          properties:
            bootstrap:
              type: integer
              minimum: 100

      # FastTree
      - if:
          properties:
            method:
              const: fasttree
        then:
          not:
            required:
              - bootstrap

required:
  - genes
  - tree