name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v7.0.0
      with:
        fetch-depth: 0
    - name: Set up Python 3.10
      uses: actions/setup-python@v6.3.0
      with:
        python-version: '3.10'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Test with pytest
      run: |
        conda install conda-forge::pytest bioconda::snakemake
        # pytest .tests/integration/test_iqtree.py
        pytest .tests/unit/test_minimap2_run.py .tests/unit/test_sam_realign_run.py
